{
 "title": "Docker Containers Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host Name",
    "query": "SHOW TAG VALUES ON \"telegraf\" FROM \"mem\" WITH KEY = \"host\""
   },
   {
    "name": "docker_container_image",
    "label": "Container Image",
    "query": "SHOW TAG VALUES FROM \"docker_container_mem\" WITH KEY = \"container_image\""
   }
  ]
 },
 "panels": [
  {
   "title": "$hostname [Docker Container STATS]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "hostname"
  },
  {
   "title": "CPU (Sum)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[$tag_host]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "query": "SELECT sum(\"usage_percent\") FROM \"autogen\".\"docker_container_cpu\" WHERE (\"cpu\" = 'cpu-total' AND \"container_image\" =~ /^$docker_container_image$/) AND $timeFilter GROUP BY \"host\",  time(10s) fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "container_image", "operator": "=~", "value": "/^$influxdb_container_image$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[$tag_host] $tag_container_image",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "container_image" ], "type": "tag" }
     ],
     "measurement": "docker_container_cpu",
     "query": "SELECT \"usage_percent\" FROM \"seven_days\".\"docker_container_cpu\" WHERE \"host\" =~ /^$influxdb_host$/ AND $timeFilter GROUP BY \"host\", \"container_name\"",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "container_image", "operator": "=~", "value": "/^$docker_container_image$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM (Sum)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[$tag_host] $docker_container_image",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "query": "SELECT sum(\"usage\") FROM \"telegraf\".\"autogen\".\"docker_container_mem\" WHERE \"container_image\" =~ /^$docker_container_image$/ AND $timeFilter GROUP BY time(10s), \"host\" FILL(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=~", "value": "/^$influxdb_container_image$/" }
     ]
    },
    {
     "alias": "MAX LIMIT: [$tag_host]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"limit\" FROM \"autogen\".\"docker_container_mem\" WHERE \"container_image\" =~ /^$docker_container_image$/ AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[$tag_host] $tag_container_image",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "query": "SELECT \"usage\" FROM \"telegraf\".\"autogen\".\"docker_container_mem\" WHERE \"container_image\" =~ /^$docker_container_image$/ AND $timeFilter GROUP BY \"host\", \"container_image\", \"container_name\"",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "=~", "value": "/^$influxdb_container_image$/" }
     ]
    }
   ]
  }
 ]
}