{
 "title": "Cluster Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host Name",
    "query": "SHOW TAG VALUES ON \"telegraf\" FROM \"mem\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[Server] $tag_host",
     "groupBy": [
      { "params": [ "cpu" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100-\"usage_idle\" FROM \"cpu\" WHERE \"host\" =~ /^$hostname$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY \"cpu\",\"host\"",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[Server] $tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "DISK",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[Server] $tag_host => /",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT \"used_percent\" FROM \"disk\" WHERE \"host\" =~ /^$hostname$/ AND \"fstype\" = 'ext4' AND \"path\" !~ /^.*zookeeper.*/ AND \"path\" !~ /^.*kafka.*/ AND $timeFilter GROUP BY \"host\", \"fstype\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "fstype", "operator": "=", "value": "ext4" }
     ]
    }
   ]
  }
 ]
}